### PR TITLE
Update CompatHelper.yml

### PR DESCRIPTION
**Pull request by devmotion**
I re-enabled CompatHelper (had missed HTTP 1) but it seems the configuration is outdated and has insufficient permissions. I updated it with the one from the CompatHelper repo.

Run of CompatHelper with the branch of this PR: https://github.com/JuliaHealth/SMARTBackendServices.jl/actions/runs/5880285094/job/15946217884

### CODE REVIEW

**Review by DilumAluthge — APPROVED** [review]

**Comment by devmotion** [comment]
Is it clear what causes the test failures? And it seems codecov is not uploaded?

More relevant for this PR: Do you have an idea why the CompatHelper fails on this branch @DilumAluthge? Might regenerating the private keys help?

**Comment by DilumAluthge** [comment]
Yeah, let me re-generate the SSH deploy keypair.

**Comment by devmotion** [comment]
Did you regenerate the keys yet?

**Comment by devmotion** [comment]
Seems CompatHelper works with the new key! Thank you @DilumAluthge!

**Comment by devmotion** [comment]
Copied from Slack:

> Coming back to the SMARTBackendServices test failures - I can reproduce them also on the master branch locally. They seem to be caused by the call in https://github.com/JuliaHealth/SMARTBackendServices.jl/blob/465e6adee8cebcd62e68e97375664a399c0a3fe2/test/basic.jl#L13, or more precisely by the request in https://github.com/JuliaHealth/SMARTBackendServices.jl/blob/465e6adee8cebcd62e68e97375664a399c0a3fe2/src/backend_services.jl#L35-L40. Based on the error message in the response I assume the error is returned at https://github.com/smart-on-fhir/smart-launcher-v2/blob/3c79b5032adc576fba2e5d4258d61d4e0f189778/backend/routes/auth/token.ts#L75. Do you have an immediate idea of what could be wrong with our request (or what has changed in smart-launcher) that could explain this error or should I keep digging?

**Review by DilumAluthge — APPROVED** [review]

**Comment by DilumAluthge** [comment]
You likely want to remove this from the merge queue. Merge queue CI won't run until https://github.com/JuliaHealth/SMARTBackendServices.jl/pull/11 is merged.

**Pull request merged**
